### ISSUE TITLE
[FEATURE] 온보딩 화면 퍼블리싱

### ISSUE THREAD

**Issue by rusia9217** [ummiih/opensw-yuyeonga#5]
## 🌴 작업 브랜치 
`feature/onboarding-ui`

## 💼 TASK 개요 

- 온보딩 시 그려지는 UI 퍼블리싱을 진행할 예정입니다.
<img width="254" alt="image" src="https://github.com/ummiih/opensw-yuyeonga/assets/156565796/c155b8b6-71b1-4419-aebe-89ff540e4330">

## ✅ TODO 및 진행현황 

- [ ] 버튼 디자인
- [ ] 하단 정렬

**Comment by ayuuuneee** [comment]
확인했습니다
